/*
Copyright 2026 The projection Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1_test

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// updateGolden regenerates the committed CRD golden files from the currently
// rendered CRDs. Invoke via `go test ./api/v1/... -update` or
// `make update-crd-golden`.
var updateGolden = flag.Bool("update", false,
	"regenerate the CRD golden files from the current rendered CRDs")

// TestCRDGolden guards the v1 API stability promise. Each rendered CRD
// (regenerated by `make manifests` before every `make test`) is compared
// byte-for-byte against a committed golden in testdata/. Any change to
// api/v1/*.go that affects a CRD schema fails this test until the goldens
// are consciously regenerated alongside the code change, forcing both to
// land in the same PR and making the schema diff reviewable.
//
// See docs/api-stability.md for the permanence commitment this test enforces.
func TestCRDGolden(t *testing.T) {
	cases := []struct {
		name     string
		rendered string
		golden   string
	}{
		{
			name:     "Projection",
			rendered: "../../config/crd/bases/projection.sh_projections.yaml",
			golden:   "testdata/crd.golden.yaml",
		},
		{
			name:     "ClusterProjection",
			rendered: "../../config/crd/bases/projection.sh_clusterprojections.yaml",
			golden:   "testdata/clusterprojection.crd.golden.yaml",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			rendered, err := os.ReadFile(tc.rendered)
			if err != nil {
				t.Fatalf("reading rendered CRD at %s: %v\n\n"+
					"Did `make manifests` run? The rendered CRD must exist before this test runs.",
					tc.rendered, err)
			}

			if *updateGolden {
				if err := os.MkdirAll(filepath.Dir(tc.golden), 0o755); err != nil {
					t.Fatalf("creating testdata dir: %v", err)
				}
				if err := os.WriteFile(tc.golden, rendered, 0o644); err != nil {
					t.Fatalf("writing golden at %s: %v", tc.golden, err)
				}
				t.Logf("updated golden at %s (%d bytes)", tc.golden, len(rendered))
				return
			}

			golden, err := os.ReadFile(tc.golden)
			if err != nil {
				t.Fatalf("reading golden at %s: %v\n\n"+
					"Run `make update-crd-golden` to initialise the golden file.",
					tc.golden, err)
			}

			if !bytes.Equal(rendered, golden) {
				t.Fatalf(`CRD schema drift detected for %s.

The rendered CRD at %s differs from the committed golden at %s.

This test guards the v1 API stability promise (docs/api-stability.md).
A diff here means your change to api/v1/*.go altered the CRD. Read the
diff carefully — if the change is a breaking schema modification (rename,
remove, or semantic change to an existing field), it is forbidden by the
stability promise and must be reverted.

If the change is additive and safe (new optional field, new condition
reason), regenerate the golden:

    make update-crd-golden

and commit the updated golden alongside your change. Reviewers will see
both the types.go change and the golden diff in one PR.

-----BEGIN rendered-----
%s
-----END rendered-----

-----BEGIN golden-----
%s
-----END golden-----`,
					tc.name, tc.rendered, tc.golden, rendered, golden)
			}
		})
	}
}
