## Append samples of your project ##
resources:
- projection_v1_projection.yaml
- projection_v1_projection_selector.yaml
- projection_v1_projection_unpinned.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
