apiVersion: projection.sh/v1
kind: ClusterProjection
metadata:
  labels:
    app.kubernetes.io/name: projection
    app.kubernetes.io/managed-by: kustomize
  name: clusterprojection-sample
spec:
  source:
    kind: ConfigMap
    name: shared-config
    namespace: config-source
  destination:
    namespaceSelector:
      matchLabels:
        projection.sh/mirror: "true"
