apiVersion: projection.sh/v1
kind: Projection
metadata:
  labels:
    app.kubernetes.io/name: projection
    app.kubernetes.io/managed-by: kustomize
  name: projection-sample
spec:
  source:
    kind: ConfigMap
    name: cm-1
    namespace: ns-1
  destination:
    name: cm-1-projection
