apiVersion: projection.sh/v1
kind: Projection
metadata:
  labels:
    app.kubernetes.io/name: projection
    app.kubernetes.io/managed-by: kustomize
  name: deployment-mirror-unpinned
  namespace: dest-ns
spec:
  source:
    group: apps
    kind: Deployment
    name: my-deployment
    namespace: source-ns
