{{- if .Values.rbac.aggregate -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "projection.fullname" . }}-namespaced-view
  labels:
    {{- include "projection.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - projection.sh
    resources:
      - projections
      - projections/status
    verbs:
      - get
      - list
      - watch
{{- end }}
