apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "projection.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "projection.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "projection.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "projection.labels" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      serviceAccountName: {{ include "projection.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: {{ include "projection.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --health-probe-bind-address={{ .Values.healthProbe.bindAddress }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
            - --metrics-secure={{ .Values.metrics.secure }}
            {{- end }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
          ports:
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.bindAddress | trimPrefix ":" | int }}
              protocol: TCP
            {{- end }}
            - name: health
              containerPort: {{ .Values.healthProbe.bindAddress | trimPrefix ":" | int }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext.container | nindent 12 }}
